version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t spark-sm:cb-java .
      - docker tag spark-sm:codebuild 686482943557.dkr.ecr.us-west-2.amazonaws.com/spark-sm:cb-java
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 686482943557.dkr.ecr.us-west-2.amazonaws.com/spark-sm:cb-java