version: 0.2

phases:
  pre_build:
    commands:
    - echo Logging in to Amazon ECR...
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
  build:
    commands:
    - echo Build started on `date`
    - echo Building the Docker image...
    - docker build -t sagemaker-sparkml-serving:2.2 .
    - docker tag sagemaker-sparkml-serving:2.2 686482943557.dkr.ecr.us-west-2.amazonaws.com/sagemaker-sparkml-serving:2.2
  post_build:
    commands:
    - echo Build completed on `date`
    - echo Pushing the Docker image...
    - docker push 686482943557.dkr.ecr.us-west-2.amazonaws.com/sagemaker-sparkml-serving:2.2
